2020-10-26 17:21:10,569 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:21:24,009 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:21:30,903 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:21:33,194 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:21:45,492 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:21:48,579 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:21:52,013 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:22:00,663 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:23:33,776 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:23:36,876 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:23:39,560 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:23:44,359 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:24:01,998 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:24:28,082 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:24:36,389 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:24:39,420 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:24:55,928 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:25:10,720 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:25:17,334 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:26:27,974 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:26:32,660 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:26:35,514 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:26:45,169 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:26:52,803 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:26:59,741 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:27:13,326 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:28:46,803 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:28:49,899 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:28:53,965 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:29:40,459 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:29:45,278 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:29:52,122 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:30:09,800 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:30:14,397 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:34:31,433 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:35:04,801 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:35:26,725 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:35:34,047 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:36:23,139 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:36:28,354 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:37:54,541 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:38:01,732 ERROR: Exception on /login [POST] [in c:\users\lx\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lx\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\mypython\blog\flaskr\routes.py", line 58, in login
    user = User.query.filter_by(username=form.username.data).first()
NameError: name 'User' is not defined
2020-10-26 17:38:04,632 ERROR: Exception on /login [POST] [in c:\users\lx\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lx\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\mypython\blog\flaskr\routes.py", line 58, in login
    user = User.query.filter_by(username=form.username.data).first()
NameError: name 'User' is not defined
2020-10-26 17:38:05,097 ERROR: Exception on /login [POST] [in c:\users\lx\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lx\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\mypython\blog\flaskr\routes.py", line 58, in login
    user = User.query.filter_by(username=form.username.data).first()
NameError: name 'User' is not defined
2020-10-26 17:38:54,291 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:40:56,125 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:41:27,422 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:42:02,635 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:42:52,347 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:43:51,838 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:44:00,916 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:44:31,236 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:45:22,581 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:45:40,003 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:45:45,436 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:46:21,810 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:48:14,258 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:48:21,021 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:51:17,076 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:52:35,891 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:52:45,990 ERROR: Exception on /user/john [GET] [in c:\users\lx\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lx\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lx\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lx\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\mypython\blog\flaskr\routes.py", line 124, in user
    user = User.query.filter_by(username=username).first_or_404()
NameError: name 'User' is not defined
2020-10-26 17:53:34,011 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:55:15,819 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-10-26 17:55:19,618 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
2020-11-03 20:19:44,281 INFO: Microblog startup [in D:\mypython\blog\flaskr\__init__.py:49]
